# Generated by Django 6.0.3 on 2026-03-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislative', '0003_bill_url_lengths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='sponsor',
            field=models.CharField(blank=True, default='', help_text='MP, Senator, or Government who introduced the bill.', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='event_type',
            field=models.CharField(choices=[('status_change', 'Status change'), ('sms_broadcast', 'SMS broadcast'), ('sms_inbound', 'SMS inbound'), ('sms_delivery_report', 'SMS delivery report'), ('ussd_hit', 'USSD hit'), ('subscription', 'Subscription'), ('vote', 'Vote'), ('system', 'System'), ('scrape', 'Scrape')], default='system', max_length=32),
        ),
    ]
