# Generated by Django 6.0.3 on 2026-03-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legislative", "0004_alter_bill_sponsor_alter_systemlog_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="document_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="bill",
            name="document_method",
            field=models.CharField(
                blank=True,
                choices=[("text", "Text extraction"), ("ocr", "OCR")],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="document_page_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bill",
            name="document_pages",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="bill",
            name="document_processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bill",
            name="document_source_url",
            field=models.URLField(blank=True, default="", max_length=2048),
        ),
        migrations.AddField(
            model_name="bill",
            name="document_status",
            field=models.CharField(
                choices=[
                    ("unavailable", "Unavailable"),
                    ("needs_ocr", "Needs OCR"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="unavailable",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="document_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="bill",
            name="document_word_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
